---
# Homepage Settings

title: Homeserver Dashboard
favicon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/home-assistant.png

background:
  image: https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d
  blur: sm
  saturate: 50
  brightness: 50
  opacity: 50

theme: dark
color: slate

layout:
  Management:
    style: row
    columns: 3
  Development:
    style: row
    columns: 4
  Databases:
    style: row
    columns: 2
  Monitoring:
    style: row
    columns: 3
  Mail:
    style: row
    columns: 3
  MCP:
    style: row
    columns: 4

providers:
  openweathermap: YOUR_API_KEY
  weatherapi: YOUR_API_KEY